name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.VPS_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "./database-cronjob/" ];then
            echo repo not exit.
            git clone https://github.com/scrum-board-352/database-cronjob.git
            cd ./database-cronjob
          else
            echo repo exit.
            cd ./database-cronjob
            git pull
          fi
          echo repo updata success

          pip install -r requirements.txt

          sh ~/add_env_value.sh
